2019-11-25 19:14:20,256 : kivy : Factory: 194 symbols loaded
2019-11-25 19:14:20,881 : kivy : Image: Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
2019-11-25 19:14:21,272 : kivy : VideoGstplayer: Using Gstreamer 1.10.2.0
2019-11-25 19:14:21,272 : kivy : Video: Provider: gstplayer
2019-11-25 19:14:21,631 : kivy : Loading MPF-MC controller
2019-11-25 19:14:21,631 : mpfmc : Mission Pinball Framework Media Controller v0.50.8
2019-11-25 19:14:21,631 : mpfmc : Mission Pinball Framework Game Engine v0.50.17
2019-11-25 19:14:21,647 : mpfmc : Machine path: D:\POKEMON - 3 - GYMS DISPLAYS
2019-11-25 19:14:21,647 : ConfigProcessor : Cache file not found: C:\Users\MISSIO~1\AppData\Local\Temp\69e9e8261b2a7a7fe237ef0e6090f00e.mpf_cache
2019-11-25 19:14:23,256 : ConfigProcessor : Loading config from file c:\python34\lib\site-packages\mpfmc\mcconfig.yaml.
2019-11-25 19:14:23,475 : ConfigProcessor : Loading config: c:\python34\lib\site-packages\mpfmc\mcconfig.yaml
2019-11-25 19:14:23,490 : ConfigProcessor : Loading config from file D:\POKEMON - 3 - GYMS DISPLAYS\config\config.
2019-11-25 19:14:23,678 : kivy : Error found in file D:\POKEMON - 3 - GYMS DISPLAYS\config\config.yaml: 'Key "slides" was defined multiple times in config   in "D:\\POKEMON - 3 - GYMS DISPLAYS\\config\\config.yaml", line 89, column 1'
Traceback (most recent call last):
  File "c:\python34\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 194, in load
    config = self.process(f)
  File "c:\python34\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 220, in process
    return yaml.load(data_string, Loader=MpfLoader)
  File "c:\python34\lib\site-packages\ruamel\yaml\main.py", line 75, in load
    return loader.get_single_data()
  File "c:\python34\lib\site-packages\ruamel\yaml\constructor.py", line 59, in get_single_data
    return self.construct_document(node)
  File "c:\python34\lib\site-packages\ruamel\yaml\constructor.py", line 68, in construct_document
    for dummy in generator:
  File "c:\python34\lib\site-packages\ruamel\yaml\constructor.py", line 481, in construct_yaml_map
    value = self.construct_mapping(node)
  File "c:\python34\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 135, in construct_mapping
    format(key, key_node.start_mark))
KeyError: 'Key "slides" was defined multiple times in config   in "D:\\POKEMON - 3 - GYMS DISPLAYS\\config\\config.yaml", line 89, column 1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python34\lib\site-packages\mpfmc\commands\mc.py", line 189, in __init__
    thread_stopper=thread_stopper).run()
  File "c:\python34\lib\site-packages\mpfmc\core\mc.py", line 95, in __init__
    self.machine_config = self._load_config()
  File "c:\python34\lib\site-packages\mpfmc\core\mc.py", line 224, in _load_config
    mpf_config = self.mpf_config_processor.load_config_files_with_cache(files, "machine", True)
  File "c:\python34\lib\site-packages\mpf\core\config_processor.py", line 111, in load_config_files_with_cache
    ignore_unknown_sections)
  File "c:\python34\lib\site-packages\mpf\core\config_processor.py", line 131, in _load_config_file_and_return_loaded_files
    config = FileManager.load(filename, expected_version_str, True)
  File "c:\python34\lib\site-packages\mpf\core\file_manager.py", line 154, in load
    return interface.load(file, verify_version, halt_on_error)
  File "c:\python34\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 208, in load
    raise ValueError(msg)
ValueError: Error found in file D:\POKEMON - 3 - GYMS DISPLAYS\config\config.yaml: 'Key "slides" was defined multiple times in config   in "D:\\POKEMON - 3 - GYMS DISPLAYS\\config\\config.yaml", line 89, column 1'
2019-11-25 19:14:23,693 : kivy : Stopping child threads... (0 remaining)
2019-11-25 19:14:23,693 : kivy : All child threads stopped.
