2020-04-25 15:58:31,283 : kivy : Factory: 184 symbols loaded
2020-04-25 15:58:31,425 : kivy : Image: Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
2020-04-25 15:58:31,492 : kivy : VideoGstplayer: Using Gstreamer 1.16.0.0
2020-04-25 15:58:31,492 : kivy : Video: Provider: gstplayer
2020-04-25 15:58:31,581 : kivy : Loading MPF-MC controller
2020-04-25 15:58:31,581 : mpfmc : Mission Pinball Framework Media Controller v0.53.3
2020-04-25 15:58:31,582 : mpfmc : Mission Pinball Framework Game Engine v0.53.3
2020-04-25 15:58:31,582 : mpfmc : Machine path: E:\POKEMON - 4 - ATTRACT AND HIGH SCORE DISPLAYS
2020-04-25 15:58:31,583 : ConfigProcessor : Config file in cache changed: E:\POKEMON - 4 - ATTRACT AND HIGH SCORE DISPLAYS\config\config
2020-04-25 15:58:31,583 : ConfigProcessor : Loading config from file c:\users\almac\appdata\local\programs\python\python36\lib\site-packages\mpfmc\mcconfig.yaml.
2020-04-25 15:58:31,638 : ConfigProcessor : Loading config: c:\users\almac\appdata\local\programs\python\python36\lib\site-packages\mpfmc\mcconfig.yaml
2020-04-25 15:58:31,649 : ConfigProcessor : Loading config from file E:\POKEMON - 4 - ATTRACT AND HIGH SCORE DISPLAYS\config\config.
2020-04-25 15:58:31,715 : ConfigProcessor : Loading config: E:\POKEMON - 4 - ATTRACT AND HIGH SCORE DISPLAYS\config\config
2020-04-25 15:58:31,722 : ConfigProcessor : Loading config: E:\POKEMON - 4 - ATTRACT AND HIGH SCORE DISPLAYS\config\player_variables.yaml
2020-04-25 15:58:31,728 : ConfigProcessor : Loading config: E:\POKEMON - 4 - ATTRACT AND HIGH SCORE DISPLAYS\config\key_mapping.yaml
2020-04-25 15:58:31,731 : ConfigProcessor : Config file cache created: C:\Users\almac\AppData\Local\Temp\c7b7ab19e78ecc520344b1352e3b06b9.mpf_cache
2020-04-25 15:58:31,731 : mpfmc : Starting clock at 60.0Hz
2020-04-25 15:58:31,747 : kivy : Text: Provider: sdl2
2020-04-25 15:58:31,791 : kivy : Window: Provider: sdl2
2020-04-25 15:58:32,659 : kivy : GL: Using the "OpenGL" graphics system
2020-04-25 15:58:32,660 : kivy : GL: GLEW initialization succeeded
2020-04-25 15:58:32,661 : kivy : GL: Backend used <glew>
2020-04-25 15:58:32,661 : kivy : GL: OpenGL version <b'4.5.0 NVIDIA 377.83'>
2020-04-25 15:58:32,661 : kivy : GL: OpenGL vendor <b'NVIDIA Corporation'>
2020-04-25 15:58:32,661 : kivy : GL: OpenGL renderer <b'Quadro 2000/PCIe/SSE2'>
2020-04-25 15:58:32,661 : kivy : GL: OpenGL parsed version: 4, 5
2020-04-25 15:58:32,661 : kivy : GL: Shading version <b'4.50 NVIDIA'>
2020-04-25 15:58:32,661 : kivy : GL: Texture max size <16384>
2020-04-25 15:58:32,661 : kivy : GL: Texture max units <32>
2020-04-25 15:58:32,678 : kivy : Window: auto add sdl2 input provider
2020-04-25 15:58:32,679 : kivy : Window: virtual keyboard not allowed, single mode, not docked
2020-04-25 15:58:32,689 : SoundSystem : SoundSystem: Using default 'sound_system' settings
2020-04-25 15:58:32,939 : AudioInterface : Initialized
2020-04-25 15:58:32,939 : SoundSystem : No audio tracks are specified in your machine config file. a track named 'default' has been created.
2020-04-25 15:58:32,941 : kivy : Base: Start application main loop
2020-04-25 15:58:32,942 : EventManager : Event: ======'display_window_initialized'====== Args={}
2020-04-25 15:58:32,942 : EventManager : Event: ======'display_top_initialized'====== Args={}
2020-04-25 15:58:32,943 : EventManager : Event: ======'display_middle_initialized'====== Args={}
2020-04-25 15:58:32,943 : EventManager : Event: ======'display_bottom_initialized'====== Args={}
2020-04-25 15:58:32,971 : mpfmc : Display: Setting 'window' as default display
2020-04-25 15:58:32,978 : EventManager : Event: ======'displays_initialized'====== Args={}
2020-04-25 15:58:32,979 : EventManager : Event: ======'slide_window_blank_created'====== Args={}
2020-04-25 15:58:32,979 : EventManager : Event: ======'display_window_ready'====== Args={}
2020-04-25 15:58:32,979 : EventManager : Event: ======'slide_top_blank_created'====== Args={}
2020-04-25 15:58:32,980 : EventManager : Event: ======'display_top_ready'====== Args={}
2020-04-25 15:58:32,980 : EventManager : Event: ======'slide_middle_blank_created'====== Args={}
2020-04-25 15:58:32,980 : EventManager : Event: ======'display_middle_ready'====== Args={}
2020-04-25 15:58:32,981 : EventManager : Event: ======'slide_bottom_blank_created'====== Args={}
2020-04-25 15:58:32,981 : EventManager : Event: ======'display_bottom_ready'====== Args={}
2020-04-25 15:58:32,992 : EventManager : Event: ======'init_phase_1'====== Args={}
2020-04-25 15:58:32,996 : EventManager : Event: ======'mc_ready'====== Args={}
2020-04-25 15:58:32,996 : EventManager : Event: ======'init_phase_2'====== Args={}
2020-04-25 15:58:32,998 : ConfigProcessor : Loading config from cache: C:\Users\almac\AppData\Local\Temp\0db36da4b9aa41dcdeae696ef4ec8d87.mpf_cache
2020-04-25 15:58:32,998 : ConfigProcessor : Loading config from cache: C:\Users\almac\AppData\Local\Temp\2476b3e7b98dcc7e56449320299b63be.mpf_cache
2020-04-25 15:58:32,999 : ConfigProcessor : Loading config from cache: C:\Users\almac\AppData\Local\Temp\32e6b619402cb4da5981e97ecb1f6408.mpf_cache
2020-04-25 15:58:33,000 : ConfigProcessor : Loading config from cache: C:\Users\almac\AppData\Local\Temp\ead1ab3e53925d446b3cb0becf429113.mpf_cache
2020-04-25 15:58:33,002 : ConfigProcessor : Config file in cache changed: E:\POKEMON - 4 - ATTRACT AND HIGH SCORE DISPLAYS\modes\attract\config\attract.yaml
2020-04-25 15:58:33,002 : ConfigProcessor : Loading config from file c:\users\almac\appdata\local\programs\python\python36\lib\site-packages\mpf\modes\attract\config\attract.yaml.
2020-04-25 15:58:33,004 : ConfigProcessor : Loading config: c:\users\almac\appdata\local\programs\python\python36\lib\site-packages\mpf\modes\attract\config\attract.yaml
2020-04-25 15:58:33,004 : ConfigProcessor : Loading config from file E:\POKEMON - 4 - ATTRACT AND HIGH SCORE DISPLAYS\modes\attract\config\attract.yaml.
2020-04-25 15:58:33,004 : kivy : Base: Leaving application in progress...
2020-04-25 15:58:33,005 : kivy : Exception while processing RegisteredHandler(callback=<bound method ModeController._load_modes of <mpfmc.core.mode_controller.ModeController object at 0x00000262853B77B8>>, priority=1, kwargs={}, key=UUID('a33714c6-25b5-47e0-bd58-548ee2f09a27'), condition=None, blocking_facility=None) for event init_phase_2
Traceback (most recent call last):
  File "c:\users\almac\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 192, in load
    expected_version_str, version_str, filename))
AssertionError: Version mismatch. Expected: #config_version=5 Actual: - duration: 20s Files: E:\POKEMON - 4 - ATTRACT AND HIGH SCORE DISPLAYS\modes\attract\config\attract.yaml

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\almac\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py", line 665, in _run_handlers
    result = handler.callback(**merged_kwargs)
  File "c:\users\almac\appdata\local\programs\python\python36\lib\site-packages\mpfmc\core\mode_controller.py", line 59, in _load_modes
    self.mc.modes[mode] = self._load_mode(mode)
  File "c:\users\almac\appdata\local\programs\python\python36\lib\site-packages\mpfmc\core\mode_controller.py", line 132, in _load_mode
    store_to_cache=self.mc.options['create_config_cache'], ignore_unknown_sections=True)
  File "c:\users\almac\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 113, in load_config_files_with_cache
    ignore_unknown_sections)
  File "c:\users\almac\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 169, in _load_config_file_and_return_loaded_files
    config = FileManager.load(filename, expected_version_str, True)
  File "c:\users\almac\appdata\local\programs\python\python36\lib\site-packages\mpf\core\file_manager.py", line 98, in load
    return interface.load(file, verify_version, halt_on_error)
  File "c:\users\almac\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 207, in load
    raise ValueError(msg)
ValueError: Error found in file E:\POKEMON - 4 - ATTRACT AND HIGH SCORE DISPLAYS\modes\attract\config\attract.yaml: Version mismatch. Expected: #config_version=5 Actual: - duration: 20s Files: E:\POKEMON - 4 - ATTRACT AND HIGH SCORE DISPLAYS\modes\attract\config\attract.yaml

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\almac\appdata\local\programs\python\python36\lib\site-packages\mpfmc\commands\mc.py", line 213, in __init__
    thread_stopper=thread_stopper).run()
  File "c:\users\almac\appdata\local\programs\python\python36\lib\site-packages\kivy\app.py", line 855, in run
    runTouchApp()
  File "c:\users\almac\appdata\local\programs\python\python36\lib\site-packages\kivy\base.py", line 504, in runTouchApp
    EventLoop.window.mainloop()
  File "c:\users\almac\appdata\local\programs\python\python36\lib\site-packages\kivy\core\window\window_sdl2.py", line 747, in mainloop
    self._mainloop()
  File "c:\users\almac\appdata\local\programs\python\python36\lib\site-packages\kivy\core\window\window_sdl2.py", line 479, in _mainloop
    EventLoop.idle()
  File "c:\users\almac\appdata\local\programs\python\python36\lib\site-packages\kivy\base.py", line 339, in idle
    Clock.tick()
  File "c:\users\almac\appdata\local\programs\python\python36\lib\site-packages\kivy\clock.py", line 591, in tick
    self._process_events()
  File "kivy\_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events
  File "kivy\_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events
  File "kivy\_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events
  File "kivy\_clock.pyx", line 167, in kivy._clock.ClockEvent.tick
  File "c:\users\almac\appdata\local\programs\python\python36\lib\site-packages\mpfmc\uix\display.py", line 205, in _displays_initialized
    self.mc.displays_initialized()
  File "c:\users\almac\appdata\local\programs\python\python36\lib\site-packages\mpfmc\core\mc.py", line 336, in displays_initialized
    self._init()
  File "c:\users\almac\appdata\local\programs\python\python36\lib\site-packages\mpfmc\core\mc.py", line 380, in _init
    self.events.process_event_queue()
  File "c:\users\almac\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py", line 752, in process_event_queue
    **event[3])
  File "c:\users\almac\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py", line 711, in _process_event
    result = self._run_handlers(event, ev_type, kwargs)
  File "c:\users\almac\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py", line 667, in _run_handlers
    raise Exception("Exception while processing {} for event {}".format(handler, event)) from e
Exception: Exception while processing RegisteredHandler(callback=<bound method ModeController._load_modes of <mpfmc.core.mode_controller.ModeController object at 0x00000262853B77B8>>, priority=1, kwargs={}, key=UUID('a33714c6-25b5-47e0-bd58-548ee2f09a27'), condition=None, blocking_facility=None) for event init_phase_2
2020-04-25 15:58:33,010 : kivy : Stopping child threads... (1 remaining)
2020-04-25 15:58:34,014 : kivy : All child threads stopped.
